---
title: "Unicare/MIIA comparisons, models"
format:
  html:
    fig.height: 2
    fig.width: 7
    fig-format: png
    fig-dpi: 300
editor_options:
  chunk_output_type: console
---

```{r knitr, warning=FALSE, echo = FALSE, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(
  cache = FALSE,
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  fig.show = TRUE,
  hiline = TRUE,
  require("knitr")
)

```

```{r, echo=FALSE, warning=FALSE, include=FALSE}
library(survival)
library(tidyverse)
library(tidymodels)
#library(ggsurvfit)
library(lubridate)
#library(ggfortify)
library(lmtest)

library(car)
library(poissonreg)

library(pscl)

library(broom)
library(broom.mixed)

```

```{r}
#| echo: false
#| label: read-files

source("read_clean.R")

```

```{r}


### Eventually will want to filter patients under observation for min number of days,
###

term <- 0
lag <- term

ibis_term <- events_full %>%
    filter(str_detect(org_name, "Unicare")) %>%
    filter(last_reminder_complete_date - first_reminder_complete_date > term) %>%
    mutate(days = last_reminder_complete_date - first_reminder_complete_date)

ibis_patients_term <- ibis_term %>%
    select(pid) %>% distinct() %>% mutate(cohort = "Unicare")


```

```{r, echo=FALSE}
#| label: MIIA term


MIIA_term <- events_full %>% filter(str_detect(org_name, "MIIA")) %>%
    filter(first_reminder_complete_date - coverage_start_date > term) %>%
    mutate(days = first_reminder_complete_date - coverage_start_date)

MIIA_patients_term <- MIIA_term %>%
    select(pid) %>% distinct() %>%
    mutate(cohort = "MIIA")

```

```{r, echo=FALSE}
#| label: ibis_events
### Ibis summaries
## round inpatient days
ibis_events <- events_full %>%
    filter(term == 0 & event_start_date > first_reminder_complete_date |
           term != 0 & event_start_date > first_reminder_complete_date &
                       event_start_date < first_reminder_complete_date + term)

    # Old:
    # filter(event_start_date > first_reminder_complete_date) # %>% ### term here!!
    # filter(event_start_date < first_reminder_complete_date + term)

### ### This breaks if one of the outcomes does not appear; eg. if term is large.

event_list <- c("emergency", "inpatient") ## in case one or more are missing

 ibis_counts <- ibis_events %>%
     mutate(event_type = factor(event_type, levels = event_list)) %>%
    group_by(pid, event_type)  %>%
    summarize(count = n(), .groups = "drop") %>%
    pivot_wider(names_from = event_type, values_from = count)  %>%
    replace(is.na(.), 0)

ibis_admit_days <- ibis_events %>%
     group_by(pid) %>% summarize(inpatient_days = round(sum(event_duration_days), 0))

ibis_events_pre <- ibis_counts %>%
    full_join(ibis_admit_days, by = "pid")

ibis_event_summary <- ibis_patients_term %>% left_join(ibis_events_pre, by = "pid") %>%
    replace(is.na(.), 0) %>%
    select(pid, emergency, inpatient, inpatient_days)

#########
```

```{r, echo=FALSE}
#| label: MIIA_events

## Get MIIA events summaries

#lag <- 439

  ## ultimately


MIIA_events <- MIIA_term %>%
    filter(term == 0 & event_start_date < first_reminder_complete_date |
           term !=0 & event_start_date < first_reminder_complete_date &
                      event_start_date < coverage_start_date + lag)

```

```{r, echo=FALSE}
#| label: patient-data
## Get patient data, HCC scores, observation times

 cohorts <- rbind(ibis_patients_term, MIIA_patients_term)
 cohorts$cohort <- as.factor(cohorts$cohort)

 patients <- report_full %>% select(pid, age, hcc, c(condition_count:urologic_cancer)) %>% 
     distinct(pid, .keep_all = TRUE) %>% filter(pid %in% cohorts$pid)

 hcc_scores <- patients %>% select(pid, hcc)

obs_times <- rbind(ibis_term, MIIA_term) %>% select(pid, days) %>% distinct()

```

-   **Unicare** combined with **Unicare-study** vs **MIIA**

## Find/Explore

Use both numerical and graphical summaries

-   Age, days and HCC score distributions, by cohort
-   Days under observation by cohort
-   Condition counts, by cohort
-   HCC scores, by cohort
-   Proportion with at least one admission, by cohort
-   number of admissions, by cohort proportions
